method_id: coxnet
family: classical
library: scikit-survival
search_space:
  alpha:
    type: float
    low: 0.000001
    high: 1.0
    log: true
  l1_ratio:
    type: float
    low: 0.05
    high: 1.0
default_params:
  alpha: 0.001
  l1_ratio: 0.5
